openapi: 3.0.0
info:
  title: API сервиса Lucky Insuranc
  description: >-
    Коллекция запросов API сервиса. Сервис предоставляет информацию об страховках для животных
  version: 1.0.1
  contact:
    name: LuckyFilms API
    url: https://lucky.com/info
    email: LuckyFilms@lucky.com
  termsOfService: https://lucky.com/terms
  license:
    name: license 1.0.1 Lucky
    url: https://lucky.com/license
servers:
  - url: https://4453f729-1913-49be-9dcc-b7a316afa17f.mock.pstmn.io
    description: Lucky Insurance Mock Server
tags:
  - name: Insurance API
paths:
  /insurance:
    get:
      tags:
        - Insurance API
      summary: Описание всех страховок для животных
      description: |
        Возвращает полный список страховых продуктов, доступных в сервисе.
      operationId: insuranceList
      responses:
        '200':
          description: список страховок
          content:
            application/json:
              schema:
                properties:
                  description:
                    type: string
                    description: Общее описание страхового сервиса
                    example: Помощь ветеринара 24/7. Онлайн консультации. Большой выбор ветклиник.
                  insurances:
                    type: array
                    items:
                      $ref: '#/components/schemas/response_200'
        '400':
          description: Некорректный запрос
        '404':
          description: Страховки не найдены
        '500':
          description: Внутренняя ошибка сервера
components:
  schemas:
    response_200:
      required:
        - type
        - details
        - price
      type: object
      properties:
        type:
          type: string
          description: Тип питомца
          example: кошка
          enum:
            - кошка
            - собака
        details:
          type: string
          description: Описание покрытия страховки
          example: Круглосуточные консультации ветеринарного врача по телефону, в чате или видеосвязи. Включена ежегодная вакцинация от бешенства.
        price:
          type: integer
          description: Стоимость страховки
          example: 50000
        currency:
          type: string
          description: Валюта
          example: рублей
        period:
          type: string
          description: Период действия страховки
          example: в год
